

USE AauLsLGGUu;

CREATE TABLE TB_LIST_CELEB (
  KEYWORD_ID INT(11) unsigned NOT NULL,
  KEYWORD_NAME VARCHAR(32) NOT NULL,
  PRIMARY KEY (KEYWORD_ID)
);


CREATE TABLE TB_BASE_RATIO (
  KEYWORD_ID INT(11) unsigned NOT NULL,
  DATE date NOT NULL,
  SEARCH_COUNT int NOT NULL,
  PRIMARY KEY (KEYWORD_ID)
);